# Generated by Django 5.0.6 on 2024-05-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stickynote",
            name="author",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="stickynote",
            name="content",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="stickynote",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
